service: serverlessSetup

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1

# functions
functions:


# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
